/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DungeonsIndexRouteImport } from './routes/dungeons/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as DungeonsIdRouteImport } from './routes/dungeons/$id'
import { Route as CharactersNewRouteImport } from './routes/characters/new'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsIndexRoute = DungeonsIndexRouteImport.update({
  id: '/dungeons/',
  path: '/dungeons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsIdRoute = DungeonsIdRouteImport.update({
  id: '/dungeons/$id',
  path: '/dungeons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/characters': typeof CharactersIndexRoute
  '/dungeons': typeof DungeonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/characters': typeof CharactersIndexRoute
  '/dungeons': typeof DungeonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/dungeons/': typeof DungeonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/characters/$id'
    | '/characters/new'
    | '/dungeons/$id'
    | '/characters'
    | '/dungeons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/characters/$id'
    | '/characters/new'
    | '/dungeons/$id'
    | '/characters'
    | '/dungeons'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/characters/$id'
    | '/characters/new'
    | '/dungeons/$id'
    | '/characters/'
    | '/dungeons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersNewRoute: typeof CharactersNewRoute
  DungeonsIdRoute: typeof DungeonsIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  DungeonsIndexRoute: typeof DungeonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/': {
      id: '/dungeons/'
      path: '/dungeons'
      fullPath: '/dungeons'
      preLoaderRoute: typeof DungeonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/$id': {
      id: '/dungeons/$id'
      path: '/dungeons/$id'
      fullPath: '/dungeons/$id'
      preLoaderRoute: typeof DungeonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CharactersIdRoute: CharactersIdRoute,
  CharactersNewRoute: CharactersNewRoute,
  DungeonsIdRoute: DungeonsIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  DungeonsIndexRoute: DungeonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
